name: release

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Calc Version
        id: version
        shell: bash
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            peteqproj/peteq-ui:${{ env.VERSION }}
            peteqproj/peteq-ui:latest
          build-args: |
            REACT_APP_API=http://localhost
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}